### ISSUE TITLE
Missing dependency make-dir on Mac OS 10.15.6 (Catalina)

### ISSUE THREAD

**Issue by diamondap** [APTrust/dart#317]
> Uncaught Exception:
> Error: Cannot find module 'make-dir'
> Require stack:
> <scrubbed>
>     at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
>     at Function.o._resolveFilename (electron/js2c/browser_init.js:281:679)
>     at Module._load (internal/modules/cjs/loader.js:690:27)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (...scrubbed...json_store.js:3:17)
>     at Module._compile (internal/modules/cjs/loader.js:967:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)

**Comment by diamondap** [comment]
Possibly fixed in https://github.com/APTrust/dart/commit/90127949081d2195b3473224560379825bd57edc. Awaiting confirmation.

**Comment by jwestgard** [comment]
Thanks, Andrew. I ran the "npm on this version and here's the result: 

 ```
Summary of all failing tests
 FAIL  plugins/network/sftp_client.test.js (7.932 s)
  ● Upload handles Permission denied

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 2

      90 |         expect(result.info).toBeNull();
      91 |         expect(result.warning).toBeNull();
    > 92 |         expect(result.errors.length).toEqual(1);
         |                                      ^
      93 |         expect(result.errors[0]).toMatch(/authentication methods failed/);
      94 |         done();
      95 |     });

      at SFTPClient.<anonymous> (plugins/network/sftp_client.test.js:92:38)
      at Client.<anonymous> (plugins/network/sftp_client.js:120:18)
      at doNextAuth (node_modules/ssh2/lib/client.js:415:12)
      at tryNextAuth (node_modules/ssh2/lib/client.js:484:5)
      at SSH2Stream.onUSERAUTH_FAILURE (node_modules/ssh2/lib/client.js:597:5)
      at parsePacket (node_modules/ssh2-streams/lib/ssh.js:3682:10)
      at SSH2Stream._transform (node_modules/ssh2-streams/lib/ssh.js:701:13)
      at SSH2Stream._read (node_modules/ssh2-streams/lib/ssh.js:253:15)

  ● Upload handles unspecfied failure

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      111 | });
      112 | 
    > 113 | test('Upload handles unspecfied failure', done => {
          | ^
      114 |     var ss = getStorageService();
      115 |     var client = new SFTPClient(ss);
      116 |     client.on('finish', function(result) {

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Object.<anonymous> (plugins/network/sftp_client.test.js:113:1)


Test Suites: 1 failed, 86 passed, 87 total
Tests:       2 failed, 571 passed, 573 total
Snapshots:   0 total
Time:        59.603 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

```

**Comment by jwestgard** [comment]
I also re-downloaded the built version and now I get a different exception:

`Error: Cannot find module 'write-file-atomic'`

**Comment by diamondap** [comment]
I moved the test problem to https://github.com/APTrust/dart/issues/318, since it's separate.

Try downloading the latest build and see if it fixes the missing module 'write-file-atomic'. We've had these problems periodically where the Electron builder doesn't always build in the correct dependencies. I hope the latest change in commit https://github.com/APTrust/dart/commit/3499de4b9e74af9dedcef9f365478f1874de76a9 fixes this issue.

**Comment by jwestgard** [comment]
This fix has resolved the issue.  The latest build launches without issues.
