### ISSUE TITLE
"Show Logs" and "About" links in the help menu are not working, as of version 2.0.21

### ISSUE THREAD

**Issue by diamondap** [APTrust/dart#534]
This affects all platforms and is due to breaking changes in the current version of Electron. 

Trying to view the logs gives this error:

/Users/diamond/aptrust/dart/ui/controllers/log_controller.js:21 Uncaught TypeError: BrowserWindow is not a constructor
    at LogController.show (/Users/diamond/aptrust/dart/ui/controllers/log_controller.js:21:25)
    at RequestHandler.handleRequest (/Users/diamond/aptrust/dart/ui/common/request_handler.js:44:66)
    at application.js:27:44
    at dispatch (jquery-3.2.1.min.js:3:10316)
    at q.handle (jquery-3.2.1.min.js:3:8343)

Trying to view the About dialog gives this error:

/Users/diamond/aptrust/dart/ui/controllers/about_controller.js:12 Uncaught TypeError: Cannot read properties of undefined (reading 'app')
    at AboutController.show (/Users/diamond/aptrust/dart/ui/controllers/about_controller.js:12:45)
    at RequestHandler.handleRequest (/Users/diamond/aptrust/dart/ui/common/request_handler.js:44:66)
    at application.js:27:44
    at dispatch (jquery-3.2.1.min.js:3:10316)
    at q.handle (jquery-3.2.1.min.js:3:8343)

**Comment by kieranjol** [comment]
Just noticed this myself on the windows build!

**Comment by diamondap** [comment]
Fixed in release 2.0.22. Downloads are available from https://aptrust.github.io/dart-docs/. 

Release notes at https://github.com/APTrust/dart/blob/master/ReleaseNotes.md
